# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('uid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('original_title', models.CharField(blank=True, max_length=200)),
                ('production_year', models.DateField()),
                ('director', models.CharField(max_length=200)),
                ('poster', models.URLField(blank=True)),
            ],
        ),
    ]
