# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
