# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20170115_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
