# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movieviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieViews',
            new_name='MovieView',
        ),
    ]
