# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movielisttitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movielisttitle',
            old_name='uid',
            new_name='year',
        ),
    ]
