# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20170115_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='title_sort',
            field=models.CharField(default='thing', max_length=200),
            preserve_default=False,
        ),
    ]
