# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_title_sort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='title_sort',
            new_name='sorted_title',
        ),
    ]
