# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20170116_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieview',
            name='ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
        migrations.AddField(
            model_name='movieview',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movieview',
            name='viewer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
