# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 14:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20170120_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieview',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
